### ISSUE TITLE
VAFT Script + Firefox. Stream Freezing

### ISSUE THREAD

**Issue by Nikralx** [pixeltris/TwitchAdSolutions#100]
I used to use the previous notify-strip that had a fix for Firefox freezing. 
Seems like the new VAFT uBlock script doesn't have that solution and every so often the stream video will freeze but audio will still work. Refreshing the page does fix this temporarily.

**Comment by pixeltris** [comment]
`notify-strip` had issues with freezing. I created `notify-swap` to attempt to fix freezing issues but it also had its own issues. If you always do a return in this function (rather than checking for firefox) the solution would be essentially identical to `notify-strip` so that might be worth trying.

https://github.com/pixeltris/TwitchAdSolutions/blob/fbd3b5e5131f4d344fd07c17b7b954f767c9e142/vaft/vaft-ublock-origin.js#L153-L154

Going to close this as the script is pulled in from the following repo where it would be better to create issues https://github.com/cleanlock/VideoAdBlockForTwitch

If the issue specific to the script version and the issue does not occur on the extension version then I can reopen and investigate.
