### ISSUE TITLE
Suggestion: Add TTV LOL PRO fork

### ISSUE THREAD

**Issue by MisterSheeple** [pixeltris/TwitchAdSolutions#109]
TTV LOL PRO contains extra features that the main TTV LOL has been lagging behind on, such as:

- Channel whitelisting
- Automatically disables proxy for subscribed channels
- fall-back to stream with ads in case the API fails

All of these features have been on the main TTV LOL's roadmap and were never implemented, as the contributors have been inactive. I think this fork shows a lot of potential, however do keep in mind that it's not yet available on the Firefox or Chrome stores.

https://github.com/younesaassila/ttv-lol-pro

**Comment by arthurbolsoni** [comment]
it's amazing how adblocks for twitch are getting complex and full of options

**Comment by EldritchEevee** [comment]
Tried, tested, recommending this to completely replace TTVLOL when it's released on the Firefox store.

**Comment by MisterSheeple** [comment]
> ~Tried, tested, recommending this to completely replace TTVLOL when it's released on the Firefox store.~
> 
> Edit: Not recommended. Adblockers conflicted, and this is merely just a fork. Just as broken.

I'm using it alongside uBO and haven't had any conflicts between the two.

**Comment by arthurbolsoni** [comment]
You can't use 2 adblock (twitch type) in same time

**Comment by arthurbolsoni** [comment]
> ~Tried, tested, recommending this to completely replace TTVLOL when it's released on the Firefox store.~
> 
> Edit: Not recommended. Adblockers conflicted, and this is merely just a fork. Just as broken.

You can't use 2 adblock (twitch type) in same time

**Comment by MisterSheeple** [comment]
> You can't use 2 adblock (twitch type) in same time

Yeah, this is true. If that's what you were doing, then you're using it wrong. Using it with standard ad blockers like uBO should be fine though.

**Comment by mewnm** [comment]
> TTV LOL PRO contains extra features that the main TTV LOL has been lagging behind on, such as:
> 
> * Channel whitelisting
> * Automatically disables proxy for subscribed channels
> * fall-back to stream with ads in case the API fails
> 
> All of these features have been on the main TTV LOL's roadmap and were never implemented, as the contributors have been inactive. I think this fork shows a lot of potential, however do keep in mind that it's not yet available on the Firefox or Chrome stores.
> 
> https://github.com/younesaassila/ttv-lol-pro

should it be used without the vanilla TTVLOL?

**Comment by younesaassila** [comment]
Hey, I'm the author of TTV LOL PRO!

I was wondering why I was getting GitHub stars all of a sudden, lol.

Just wanted to bring in a few clarifications:
- This is a fork of the TTV LOL extension. It still uses the same back-end server and thus experiences the same server issues as the official TTV LOL extension. This also means it should be used as a replacement to the default TTV LOL extension to avoid conflicts.
- I'm not uploading this fork to the Firefox Add-on Store anytime soon, because I fear it would become sort of "the new official extension" and I would be treated as the new maintainer when having both zero access to the back-end and no will to deal with all of TTV LOL's problems.

Also, on a more personal note, I don't really see the benefits of server-side ad-blocking solutions anymore. They're really unstable and client-side solutions work just fine. I don't think the development/featuring of these solutions is a priority.

**Comment by pixeltris** [comment]
Done.
