### ISSUE TITLE
Vaft uBlock script doesn't work anymore.

### ISSUE THREAD

**Issue by Divzed** [pixeltris/TwitchAdSolutions#118]
Purple screen when I try to open someone stream.
Location: Central EU

[Vaft](https://imgur.com/IKXpLlM)

Seems like twitch patched something.

/Edit
"video-swap-new" also doesn't seem to work.

[video-swap-new](https://imgur.com/3ie2oGZ)

**Comment by cleanlock** [comment]
Yup, Twitch pushed a player update.

**Comment by llaurenss** [comment]
TTV LOL extension works but doesnt block mid-roll ads

**Comment by Divzed** [comment]
> TTV LOL extension works but doesnt block mid-roll ads
Yeah I noticed that too. Blocks entry ads but mid-rolls ads are still present. Amazon tries to squeeze Q4 ad rev to maximum.

**Comment by pixeltris** [comment]
The local solutions which utilized alternative ad-free streams have been closed off by Twitch. The full ad message is expected and mentioned in the README for both solutions.

`video-swap-new` is essentially the same as `vaft` with a slight difference in how it accesses the stream. This was done because there was a freezing issue which would require the user to manually fix.

If `TTV LOL` isn't working for midrolls you could try this instead https://greasyfork.org/en/scripts/425139-twitch-ad-fix/code (this is the Falan proxy under `Video Ad-Block, for Twitch`). Or try your own proxy / VPN.
