### ISSUE TITLE
Dyn-skip no longer working for preroll ads

### ISSUE THREAD

**Issue by paulcdejean** [pixeltris/TwitchAdSolutions#14]
Yesterday it seems to make it so preroll ads were skipped, but it's not working today.

**Comment by kivle** [comment]
I switched to the -alt version of the midroll script earlier this week, and it's been working nicely for me thus far. Before that I used the `dyn` script, but earlier this week it started freezing the video all the time. It definitely looks like they are changing things these last few days.

**Comment by pixeltris** [comment]
I'm currently rarely getting ads so it's hard for me to test. It might be that they increased the delay between notifying that an ads was watched and accepting it. Or they might have added a check ensure that watch notifications are only accepted if they fit within a certain timeframe of when it expects it to be seen.

@kivle `dyn` and `dyn-skip-midroll-alt` use the same ad-stripping technique when the skipping portion fails. That ad-stripping technique needs improvements. The biggest issue with it is when it loops segments. The problem with the main embedded ad-stream is that it appears to be way ahead of the other variants. I haven't figured out why this is the case. When it can't keep up this will either cause freezing or looping of segments.

**Comment by kivle** [comment]
Oh, I didn't know both used the same technique. Changing to the -alt variant definitely stopped the freezing for me though, so there seems to be some sort of difference.

**Comment by pixeltris** [comment]
Yea using `dyn-skip-midroll-alt` is significantly better, assuming the skip portion works, as this ends up not having to use the ad-stripping technique.

**Comment by pixeltris** [comment]
@paulcdejean I just got served an ad, and it seems to work for me (skipped correctly). I might need to add some adjustments / delay because the current implementation is somewhat dependent on your ping. It makes 2 requests to check for ads, and notifies ads were watched. If this all completes too quickly then by the time it requests the main stream the server might not have fully processed it and give you an ad anyway. Simply refreshing the page should somewhat solve the issue (they tend not to give repeat ads if you watched/skipped one recently).

**Comment by pixeltris** [comment]
I observed this behavior today. Skipping would fail, and refreshing wouldn't immediately resolve the issue. Though it seems that the server still somewhat processes the ad-skipping request because after what I assume is the ad duration I no longer see ads after refreshing (like in the case of the regular `dyn` script).

**Comment by pixeltris** [comment]
Here's some more info:

- Never notifying that ads were watched (i.e. in the `dyn` scenario) will always result in ads on every stream.
- Notifying that ads were watched will be accepted by the server, but ads will keep being served until a period of time passes (I assume the ad duration length, regardless of how many notifications you send).

I'll update the README to reflect the change in the `dyn-skip` variants.

**Comment by paulcdejean** [comment]
I'm reading the new README now and I don't understand the current state of things.

What dyn-skip-midroll-alt is doing makes sense, but what about PREROLL ads? Preroll ads are what I'm concerned about. Midroll adds support the streamer, since they're run by the streamer during ad breaks, but preroll ads just go entirely to twitch.

Does dyn-skip-midroll-alt only skip midrolls while not skipping prerolls? Is there any option that only skips prerolls?

**Comment by pixeltris** [comment]
The naming is a bit screwed up because things have changed a little. I'm reluctant to change the names of things as I provide master branch links which would break if I changed the naming.

`dyn-skip-midroll-alt` notifies Twitch that ads have been watched. Twitch has changed their server side code to only fully acknowledge this after the duration of the ad has elapsed (i.e. it doesn't fully skip prerolls anymore). The script will play a low-resolution stream for this period. You generally shouldn't see prerolls for a while after Twitch acknowledges the request but YMMV.

None of the userscript/ublock scripts currently fully solve either preroll, or midroll ads.

`Twitch AdBlock` linked at the top of the README should skip both preroll and midroll ads.

`ttv_adEraser` can skip prerolls, but it's somewhat dependent on whether Twitch is currently serving the purple screen. If purple screen is active server side then you will see the purple screen. Again YMMV.

**Comment by pixeltris** [comment]
These scripts were renamed in https://github.com/pixeltris/TwitchAdSolutions/commit/c3e1ee390ae684fe47d5159c689332d53e67094d to reflect that change that it no longer skips ads, but instead notifies that they were watched (reduces preroll frequency).

`notify-strip-reload` or `notify-reload` should probably the shortest waiting period to get the real stream.
