### ISSUE TITLE
[Question] Why is Dyn-Skip getting deprecated if it does work?

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#15]
I speak from experience here, have been using it since day 1 and the worst that happened is that about once or twice per day I get Error #2000 from Twitch, nothing else. Why is it getting deprecated in favor of ones that are detrimental by varying degrees to the viewing experience?

**Comment by pixeltris** [comment]
Twitch does a lot of A/B testing so you might still be able to successfully skip preroll ads with `dyn-skip`.

As noted in https://github.com/pixeltris/TwitchAdSolutions/issues/14 Twitch is rolling out new server code which results in `dyn-skip` not skipping ads. In the case of `dyn-skip` the `mute-black` fallback will kick in (you'll see a black screen). This would be no different from just using `mute-black` instead of `dyn-skip`.

My assumption is that their A/B testing phase will come to an end within a month and it will be their defacto implementation. If that isn't the case then I could leave it up.

You can always obtain a permalink for any implementation. For example the latest commit is https://github.com/pixeltris/TwitchAdSolutions/tree/c3e1ee390ae684fe47d5159c689332d53e67094d

Replace `master` in any of the original urls with the commit hash. For example `dyn-skip` ublock origin permalink would be https://github.com/pixeltris/TwitchAdSolutions/raw/c3e1ee390ae684fe47d5159c689332d53e67094d/dyn-skip/dyn-skip-ublock-origin.js

**Comment by pixeltris** [comment]
These scripts have now been removed.

As mentioned use the commit history for testing older scripts. If you find that some methods still provably work then I can reintroduce them where appropriate.
