### ISSUE TITLE
Is twitch cracking down hard now?

### ISSUE THREAD

**Issue by Sirlansolot** [pixeltris/TwitchAdSolutions#159]
None of these work for me. Firefox or Chrome. In the past when they stopped working I could still re-fresh pause/play to get it working. Between the new changes and agressive pre-rolls and ad's it feels like twitch is trying to kill themselves. 

I'm subbed to 11 channels, you'd think I'd be able to click on another channel without waiting 2mins just to see wtf it is. Time to cancel everything.

**Comment by BURGERxBOY** [comment]
just to show that twitch has been enforcing stuff like that more frequently as of late, and those alterations might be what's causing the issue with the ad pre-rolls.

-- if they've gone to the extent of changing the site UI just for something like the turbo service, they'll likely be changing even more soon.

sadly, the odds are those changes won't be for the better. - given the recent mass browser extension incompatibility their update caused not long ago.

-- from what i saw, it affected extensions like FFZ / BTTV / alternate player for twitch tv / ublock origin / and even tampermonkey, or at least its userscripts.

hopefully twitch doesn't keep up this patching pace, otherwise we may not be able to find an stable countermeasure.

**Comment by pixeltris** [comment]
I haven't noticed anything new from Twitch in the past 6 months. The 31st May issue which impacted some ad blocking methods was a side effect of them wanting to thwart third party clients/apps.

Prerolls can increase in frequency based on how much ad space is being bought.
