### ISSUE TITLE
Out of sync video / audio on notify-strip

### ISSUE THREAD

**Issue by hoffmc3** [pixeltris/TwitchAdSolutions#17]
After an ad is skipped using notify-strip, audio and video are significantly out of sync until there is a manual player refresh.  This has been occurring for about a month - the most recent change "Fix buffering issue after ad segments" did not resolve this for me, and it was happening since one of the updates before that.  It was not doing this originally though, the sync issue popped up only a few releases ago.  I'm using the userscript with Tampermonkey. 

I've been using the other Twitch AdBlock add-on instead of notify-strip for the past month, however that one actually buffers more frequently for me than notify-strip. But today - ads started getting past Twitch AdBlock, so I returned to notify-strip, but the audio sync issue is still happening.  Any thoughts? Thanks!

**Comment by pixeltris** [comment]
I'm sure there will be a fix for `Twitch AdBlock` soon. That one generally shouldn't cause buffering issues as only the initial m3u8 is proxied. It does change the geographical location where m3u8 files are fetched from (I think to a Twitch EU server). I guess that could potentially cause buffering depending on your location and internet speed.

`notify-strip` modifies the sequencing of segments when there are ads. I'm not sure how I could fix audo desync as the actual content of the segments isn't modified, that's handled by the Twitch player itself.

There was a different algorithm previously that didn't mess with sequencing, but had various issues like looping/stuttering whilst ads play. You can still find it [here](https://github.com/pixeltris/TwitchAdSolutions/blob/aca0ad8b7dfd11df966b00f1e04edc6f0f799d3e/dyn/dyn.user.js). However, this doesn't notify Twitch that ads were watched. It might be worth checking anyway to see if it fixes desync issues.

Alternatively you could try `Alternate Player for Twitch.tv` which hides ads, or `mute-black` which does something similar (https://github.com/pixeltris/TwitchAdSolutions/pull/16 is a better version of `mute-black`).

**Comment by hoffmc3** [comment]
I'm using the old algorithm now and it works far better for me.  I get maybe a 1-2 second buffer during ads, but no looping and after the ad finishes everything looks great.  Not sure what other people's experiences are, but I'd rather have a little bit of buffering that resolves itself over out of sync audio requiring manual reload.  Though I don't think I've tried notify-strip-reload - but wouldn't that one cause you to miss content if your stream delay gets shorter after the reload?

Not really relevant to this script, but the more specific issue I've been having with Twitch AdBlock is that it just pauses for about 15 seconds when a midroll ad comes up.  Then when the ad ends it resumes, with me now on a huge delay.  Not sure if others were seeing this or just me.  Again, 1 second of buffering is better than 15 seconds of freezing.

**Comment by pixeltris** [comment]
Current algorithm on `master`:

https://github.com/pixeltris/TwitchAdSolutions/blob/aca0ad8b7dfd11df966b00f1e04edc6f0f799d3e/notify-strip/notify-strip.user.js#L397-L445

Previous algorithm (it's actually 2 algorithms, but `OPT_MODE_STRIP_AD_SEGMENTS_NEWEST` is enabled here):

https://github.com/pixeltris/TwitchAdSolutions/blob/c3e1ee390ae684fe47d5159c689332d53e67094d/notify-strip-reload/notify-strip-reload.user.js#L285-L350

The new algorithm reconstructs the m3u8 during ad segments, and when the ad segments are over it continues to modify the sequence number which is required due to the initial m3u8 modifications. The full m3u8 reconstruction step might be set up incorrectly which may be introducing the audio desync.

`notify-strip-reload` needs some improvements, it doesn't quite do what it's supposed to. That one could be changed to basically invoke the player reload when it sees live non-ad stream segments coming in. Currently it does a full player reload which can result in more ads, and doesn't have decent enough detection of when the ad is actually finished.

I could update the README to link to the previous scripts for those who suffer similar audio issues. I'll have to re-introduce the old code to `master` if Twitch makes breaking changes.

**Comment by hoffmc3** [comment]
Yes I just use FFZ's reload player to fix sync, not refreshing the whole page.  Otherwise the point stands though.

Anyway thank you for the old version.  I'm good with this for the moment, and I've made you aware of the audio sync issue.  I really appreciate you building this, as mentioned I personally find this to be the best solution out there. If you want to look into fixing the audio sync on the current algorithm, or making the previous algorithm more available on master, I think that's a good idea.  Other than that let me know if I can help with any testing, or you can close this issue (or leave it open to work on).  Thanks again!

**Comment by pixeltris** [comment]
FFZ could potentially be the reason why there's audio latency. It uses [createDynamicsCompressor()](https://github.com/FrankerFaceZ/FrankerFaceZ/blob/0d433c3ebd5e8a824b680c3f8e5d634a0267aaca/src/sites/shared/player.jsx#L1064) to help with audio levels. Possibly the m3u8 modifications are messing with the audio compressor. I'll look into it at some point.

**Comment by Qrokqt** [comment]
I have the same issue, even with FFZ disabled theres still a sync issue. Stopping and starting the player a few times fixes it.

**Comment by pixeltris** [comment]
Yea I've noticed this too. But I haven't had enough ads lately to fully investigate the issue.

The scripts here might fix the audio desync (at the cost of a less smooth 480p->src resolution transition) https://github.com/pixeltris/TwitchAdSolutions/tree/c3e1ee390ae684fe47d5159c689332d53e67094d/notify-strip

**Comment by switchersx** [comment]
> 
> 
> Yea I've noticed this too. But I haven't had enough ads lately to fully investigate the issue.
> 
> The old script here might fix the audio desync (at the cost of a less smooth 480p->src resolution transition) https://github.com/pixeltris/TwitchAdSolutions/tree/c3e1ee390ae684fe47d5159c689332d53e67094d/notify-strip

Using this one solved the desync for me (FF Audio compressor enabled, Ublock origin, Firefox).

**Comment by Rage-X** [comment]
I actually initially experienced video desync when switching from low res to high res after the ad is done (probably months ago).

But recently I noticed that it transitions perfectly and there is no longer any jump in the video.

**Comment by pixeltris** [comment]
Hopefully fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/f37af091928cc4c93375047d72195aae4b31e4bd if the issue persists feel free to reopen this.

**Comment by TsukiZero** [comment]
Unfortunately, the issue persists and got times worse for me, to the point it randomly starts replaying 1 or 2 seconds of an audio portion while the video goes on, delaying it by something between 6 seconds and 12 seconds. It was so bad that I had to try other ad solutions in the meantime (add-on ones that is), including Purple Twitch TV (which had the off-chance of getting stuck in buffer or halting a stream entirely) and Video Ad-Block (which works, but the shifts between qualities are annoying)

**Comment by pixeltris** [comment]
That's interesting, could you try this [ublock](https://gist.githubusercontent.com/pixeltris/3aba32b42c24bda8f56316729dea66b6/raw/43389763af099813d6686c739cb4cfb89458dfe3/pause-play-notify-strip.js) / [userscript](https://gist.github.com/pixeltris/9e2a3ed75efd8c79d01ec2980a93363c/raw/412bf34dc1868d93b5bf9eca2784e60fcc4263b3/pause-play-notify-strip.user.js) (uses a pause/play rather than fiddling with play state).

Does it happen on all streams? Or only certain streams? If so which streams? And which browser do you use?

**Comment by Rage-X** [comment]
I've been paying attention to this, no issues to report on my end. Once the "ad" section with the low res stream ends, the low res stream transitions to high res flawlessly without any desync.

**Comment by TsukiZero** [comment]
Started testing the 1.5 you linked, pixeltris. I'll be sure to inform of any issue as I see them.

**Comment by pixeltris** [comment]
I'm going to close this again. I'm pretty sure with the current algorithm there aren't any desyncs.
