### ISSUE TITLE
Is Stream Cleaner legitimate?

### ISSUE THREAD

**Issue by misternebula** [pixeltris/TwitchAdSolutions#171]
Link : https://chrome.google.com/webstore/detail/stream-cleaner/lehcglgkjkamolcflammloedahjocbbg

It seems to block ads fine, but some people have said it's a data farming extension? I've looked through all the javascript and nothing seems out of place.

**Comment by revunix** [comment]
That looks fishy af

**Comment by EatingCarBatteries** [comment]
I am not going to go off of the source code because I do not know JavaScript -  

the website itself looks kind of fishy:
- (probably, generic names, bad spelling, overly positive (in a realistic scenario, people would be complaining because all twitch blockers don't work perfectly)) fake reviews:
 
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/40326108/aaab6c3c-81bb-44cd-bb89-3000a3a22345)

- the privacy policy is **very likely** copy and pasted (they state on the chrome web store that they don't collect information, but on their privacy policy they say they collect and use data, even with a CCPA data rights section)
- There is no contact information on the website, even though they tell you to contact them on their privacy policy (their email can be found on the chrome web store)
- There is no place to donate to the developer, and no features are behind a paywall.

**Comment by pixeltris** [comment]
I wouldn't recommend using it.

Look at the manifest:

https://robwu.nl/crxviewer/?crx=https://chrome.google.com/webstore/detail/stream-cleaner/lehcglgkjkamolcflammloedahjocbbg&qf=manifest.json

Compared to the original:

https://github.com/cleanlock/VideoAdBlockForTwitch/blob/master/chrome/manifest.json

The manifest adds these additional permissions: `notifications`, `tabs`, `gcm` and runs the `content.js` script on EVERY page `"*://*/*"`.

Then look at these files:

https://robwu.nl/crxviewer/?crx=https://chrome.google.com/webstore/detail/stream-cleaner/lehcglgkjkamolcflammloedahjocbbg&qf=background.js
https://robwu.nl/crxviewer/?crx=https://chrome.google.com/webstore/detail/stream-cleaner/lehcglgkjkamolcflammloedahjocbbg&qf=content.js

This requires the user to go to a certain website or page with an ad made by them or their partners which will trigger their notification code. This is used to target people who are not familiar to trick them into some type of action. On operating systems look Windows this looks quite official with the notifications popping up as system notifications. It isn't clear what type of notifications are sent as this needs to be paired with additional web page scripts.

Does the ad blocking work? Yes. It uses the VAFT script:

https://robwu.nl/crxviewer/?crx=https://chrome.google.com/webstore/detail/stream-cleaner/lehcglgkjkamolcflammloedahjocbbg&qf=ads.js

Google should do a better job of auditing their extensions.

**Comment by dpthegrey** [comment]
`Stream Cleaner` does work better than recommended `ttv lol pro` though and is free. I haven't had any buffering issues with stream cleaner, Whereas in `ttv lol pro` there are limited amount of proxies so at some point either it will buffer or slip an ad due to the limit in free version (you can find issues about that on internet or extension comments section), surely you can increase number of proxies by donating to the author to get access to more proxies if you like. 

Stream Cleaner also shows `blocking ads...` status in top left corner of video player when ads show up and it starts blocking. I wouldn't mind **using in a new profile**, if you are concerned about the permission it requires i would recommend creating a new browser profile.

![image](https://github.com/pixeltris/TwitchAdSolutions/assets/49444980/1e5d3124-3644-401c-9fa5-f4c92fbe2e3d)

**Comment by Geczy** [comment]
stream cleaner works sooo good lol, ttv lol pro is awful

**Comment by FURTEK-SV** [comment]
Google just killed this on their store because it contains Malware, it's disabled now. I'm so sick of this garbage. They can just kill an extension because they don't like it or it blocks ads too much.

**Comment by davidmwhynot** [comment]
What "malware" did this contain? Is it just the ad farming stuff mentioned here? Google gives basically no information other than "it's malware" which is so unhelpful it's frustrating. Was I being keylogged? CPU used for crypto farming? Personal data harvested? One of these things is way worse (IMO) than others. If I was being keylogged, I now need to change a bunch of important passwords. If my cpu was just being used for crypto mining, that sucks but it's w/e.

**Comment by LordSheep** [comment]
> What "malware" did this contain? Is it just the ad farming stuff mentioned here? Google gives basically no information other than "it's malware" which is so unhelpful it's frustrating. Was I being keylogged? CPU used for crypto farming? Personal data harvested? One of these things is way worse (IMO) than others. If I was being keylogged, I now need to change a bunch of important passwords. If my cpu was just being used for crypto mining, that sucks but it's w/e.

Yeah I regret having downloaded that extension. I have no idea how long I ended up enabling the extension. And now I don't even know how serious the problem is.
