### ISSUE TITLE
i need help, this goes over my head

### ISSUE THREAD

**Issue by TheBenShee** [pixeltris/TwitchAdSolutions#173]
i'm currently using the url "https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js" for the script and did everything like it was said in the read me for adding a script.

now whenever the ad runs, the stream is in 360p. how do i change that? i have absolutely no idea about github or how/where to save the whole code and make it a new url or anything. i tried to add the whole code as a filter in ublock but htat wasn't it. i know where to change what in the code to get rid of the 360p and make it Source (i think) but yeah...

can someone help me by explaining where to do what please?

thanks

**Comment by pixeltris** [comment]
I'm not sure what your question is. It sounds like you've got the script working and you know how to remove it if you want it removed. It runs at 360p during ads by design.

If you'd like a solution which doesn't alter the resolution you want to look at to use a proxy solution. The best currently is https://github.com/younesaassila/ttv-lol-pro

All the ad blocking solutions have trade-offs / none are perfect.
