### ISSUE TITLE
Vaft and video-swap-new script need daily purge & update in ublock to work ? Getting ads everyday in Twitch.

### ISSUE THREAD

**Issue by Elaws** [pixeltris/TwitchAdSolutions#200]
I tested `vaft` and `video-swap-new` scripts and unfortunately I get ads every day in Twitch. Sometimes, after purging and updating the filters in ublock, the ads disappear. But for a week I've had to do this everyday : is this the expected behavior ?

Thank you.

**Context :** 

- Firefox v. 119.0
- Ublock origin v. 1.53.0
- Windows 11 build 22621

- My filters : 

```
twitch.tv##+js(twitch-videoad)
```

- Ublock advanced settings : 

```
userResourcesLocation https://github.com/pixeltris/TwitchAdSolutions/raw/master/video-swap-new/video-swap-new-ublock-origin.js
```

**Comment by RedSnt** [comment]
µBlock has been aggressively been updating Youtube adblock lately, might be related to that requiring daily updating somehow?

**Comment by Elaws** [comment]
> Try using permalink.
> 
> You should add the filter and resource link, and it should just work. Without a need for purge-update, because there are no updates for Twitch filters.

Thanks : isn't it what I already did ? I followed procedure described here : https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin.

**Comment by gwarser** [comment]
Try using the link marked "ublock (permalink)". The auto-updated one have redirection, maybe this causes issues.

**Comment by pixeltris** [comment]
Yea that seems to happen semi often. It could indeed be that redirect. I'll update them at some point to avoid the redirect.

**Comment by spencerharmon** [comment]
Using the ublock url (not permalink) I also got an ad today for the first time in a while. If it happens again, I'll change to permalink and update here.

**Comment by Teapsalm** [comment]
I've tried literally all of the "solutions" and none of them have worked for some time. Twitch won.

**Comment by Suprcheese** [comment]
> I've tried literally all of the "solutions" and none of them have worked for some time. Twitch won.

Vaft still works for me.

**Comment by cheatreal321** [comment]
Same issue here, been getting ads again for the last few weeks and I've tried disabling and re-enabling uBlock, cache purges and refreshes, countless browser restarts, different links under userResourcesLocation, but everytime I try to `window.reloadTwitchPlayer` it prints `undefined`

**Comment by Gamerboi520** [comment]
@pixeltris whats the right way to set these because im still getting ads?
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/bd1f0471-8263-42df-bf39-3e243f03e27e)
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/fa6fef6e-6316-4915-8062-f18c947d3fca)

**Comment by Gamerboi520** [comment]
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/26d647dd-e179-4298-b7c6-d6fd3edddc47)

**Comment by pixeltris** [comment]
That should work. You probably don't want to put the url in the filter list itself but it probably shouldn't have any impact. As mentioned in this issue uBlock Origin stops applying the script after some time. This persists perpetually once it happens. You used to be able to purge to fix it but I'm not sure how you'd fix it since they removed that functionality. I can't really help beyond this info unfortunately.

**Comment by Gamerboi520** [comment]
> That should work. You probably don't want to put the url in the filter list itself but it probably shouldn't have any impact. As mentioned in this issue uBlock Origin stops applying the script after some time. This persists perpetually once it happens. You used to be able to purge to fix it but I'm not sure how you'd fix it since they removed that functionality. I can't really help beyond this info unfortunately.
I assume this is the correct way to set up the userscripts?
![image](https://github.com/pixeltris/TwitchAdSolutions/assets/84089845/03f8adec-9764-40cf-ba5c-455af889f8ac)

**Comment by pixeltris** [comment]
Closing as I don't have any plans to look into this.

As far as I know something causes uBlock Origin to stop injecting the script after some time. Refresh / new tabs don't help. When the purge button existed that would fix it but I assume now the only way to fix it is to disable / enable the extension (not 100% sure). To fix this issue you would need to do some debugging somewhere in uBlock Origin and create a PR over there.

Its been a while since I properly tested the scripts so if this is already fixed or if it gets fixed in the future feel free to leave a comment below and I'll remove the note in the README:

> *The scripts __may randomly stop being applied by uBlock Origin__ for unknown reasons ([#200](https://github.com/pixeltris/TwitchAdSolutions/issues/200)). It's recommended to use the userscript versions instead.*
