### ISSUE TITLE
Vaft script - getting random muted

### ISSUE THREAD

**Issue by iznawh** [pixeltris/TwitchAdSolutions#207]
Hi,

While watching the stream the stream will just randomly mute itself and never unmute itself. I understand its suppose to mute during the ad swap thing, but its not even blocking ads when it happens. I have the script installed in tampermonkey and it is version 5.8.5

**Comment by pixeltris** [comment]
I don't think the `vaft` script does anything with muting. The `video-swap-new` script can in some cases be impacted where you mute one tab and then another tab becomes muted after a player reload due to an ad but the `vaft` script doesn't have this logic so I'm not sure where the muting is coming from.

**Comment by semtious** [comment]
yeah I have been having the same issue has been facing. It's been happening for a quite a while too. if you click the play pause button an extra time after its muted it usually unmutes again and sometimes you have to do it manually.

**Comment by iznawh** [comment]
i somewhat fixed it by changing 
 player_volume: 0 -> 25

**Comment by pixeltris** [comment]
I've never been able to reproduce this one but I'm closing this as I'm consolidating all playback issues for `vaft` into #164
