### ISSUE TITLE
Midroll ads, quality lowered

### ISSUE THREAD

**Issue by royoungs** [pixeltris/TwitchAdSolutions#217]
Hello!
The JS is successfully blocking the midroll ads, but the quality of the stream is TANKING when they're active. Any fix for this?

**Comment by pixeltris** [comment]
It's unfortunately a drawback of how it works. The `vaft` script tries to get a clean stream faster but it suffers from various playback issues due to how it inserts the stream segments.

I keep meaning to update the README with this info but I just haven't got around to it.

I'd recommend trying `TTV LOL PRO` which wont lower the quality https://github.com/younesaassila/ttv-lol-pro
