### ISSUE TITLE
Vaft userscript on firefox testing

### ISSUE THREAD

**Issue by izar3** [pixeltris/TwitchAdSolutions#222]
_I am using violetmonkey addon and get varied results with the vaft userscript_

Here are some tests I have done changing violetmonkey injection modes, what I hope is useful information:

_Synchronous page mode:_
This setting works the best when a midroll ad starts but desync will occur after midroll ads. instant injection is to soon function findReactNode() and fails to find the videoPlayer, so it does not pause then play after ads what causes sync issues

_Alternate page mode for firefox (default for violentmonkey):_
Video always freezes during ads. The video resolution of the player changes a few times causing it to freeze. Resumes fine after ad is finished

_Alt mode and Synchronous mode both off:_
Infinite Buffer when a midroll ad starts. Manual pause then play fixes it. Resumes fine after ad is finished

_solution?:_
I think if the script uses Synchronous page mode then pause then play after "blocking ads" overlay is removed from the video player this script will run flawless because I saw 2-3 midrolls over a few hours and I manually paused then played after each ad to fix the desync and it worked without issues

ty

**Comment by pixeltris** [comment]
> findReactNode() and fails to find the videoPlayer

This is due to #220 and should be fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/9bd481a833341911ac39412dc4abcc41f911af8f

I'm not sure if the freezing issues are also related or not. There have been other freezing related issues for a while though so I'm going to close this in favor of the already open issues #119 / #164
