### ISSUE TITLE
Suggestion for vaft: Have a version to allow banner ads

### ISSUE THREAD

**Issue by hoffr** [pixeltris/TwitchAdSolutions#273]
banner ads that show up under the video have started appearing for me and since they aren't disruptive i'd like to support the channels i watch by enabling them, if that's at all possible

**Comment by preynolds2** [comment]
You mean you want to support twitch.

**Comment by zGato** [comment]
If your intention is to support the streamers, then just donate to them directly, neither via Turbo nor Subscriptions since Twitch takes a huge cut.

By the way, AFAIK vaft/video-swap-new does not block those banner ads but uBlock Origin does. And I highly doubt the streamer will get a single cent of revenue from those sponsored banner ads, Twitch's probably getting 100% of it.

**Comment by pixeltris** [comment]
As mentioned the scripts only handle SSAI. You want to look at modifying your adblocker filter lists.
