### ISSUE TITLE
ads with video-swap-new v1.29 on firefox when opening in background tab

### ISSUE THREAD

**Issue by yvawt** [pixeltris/TwitchAdSolutions#277]
when opening a stream in a background tab ads will play when you switch to that tab
i've rolled back to version 1.28 and ads no longer get through
edit: using the userscript version with violentmonkey

**Comment by stevenya97** [comment]
@pixeltris Noting this here since it's related to the new commits. Getting some playback issues with both vaft and video-swap new userscripts that didn't happen prior to the new commits.

Midroll screens are either black or stuck on a frozen frame. Once midrolls are over i do see `Finished blocking ads` message and the stream plays again. Observed mostly with vaft but will report back if I see this with video-swap-new.
![Screenshot 2024-08-21 131019](https://github.com/user-attachments/assets/86e49896-0926-42ec-8f70-8a96bb985bb9)
![Screenshot 2024-08-21 130330](https://github.com/user-attachments/assets/21cf2171-f57d-4342-92a0-883e325b4501)
![Screenshot 2024-08-21 130313](https://github.com/user-attachments/assets/35dedda8-5a99-40ea-b85d-0abe7c488d87)

**Comment by stevenya97** [comment]
Hmm, tried vaft userscript in another browser and midrolls switched with no issue and got this output.
![Screenshot 2024-08-21 at 2 31 21 PM](https://github.com/user-attachments/assets/3f1a3d8f-8989-40ed-8b08-4c46101e43b6)

**Comment by stevenya97** [comment]
This all might belong in #226 instead. Am seeing this message in console that is likely vaft related. 
![Screenshot 2024-08-21 145038](https://github.com/user-attachments/assets/e06781ca-320a-4eba-9705-02e615325d0a)

Strange I can reliably get the freezing issue with the updated commit despite vaft being issue free previously for me.

**Comment by pixeltris** [comment]
Fixed in https://github.com/pixeltris/TwitchAdSolutions/commit/0863c6d74b98b5e8349382f508412a9005f50c57

@stevenya97 that's pretty strange as nothing changed in terms of what the script does other than checking if another script is already active. But yea, playback problems belong in the already open issues

**Comment by stevenya97** [comment]
Gotcha👍🏻 Yeah I've always stuck with `video-swap-new` as it tends to have less issues than `vaft`, but it was indeed strange as I try to test `vaft` after any new commits and haven't had this many freezes before. No worries as `video-swap-new` works in the meantime. 

On the side, is there a solution to the reported stream latency to broadcaster stat? It always reports a negative value in `video-swap-new` while `vaft` seems to get a proper value. Is this a known limitation?
![Screenshot 2024-08-21 172947](https://github.com/user-attachments/assets/d3d66113-4b53-41d6-a7ce-d1670da6f9c7)

**Comment by pixeltris** [comment]
The latency thing is weird, it's mentioned here https://github.com/pixeltris/TwitchAdSolutions/issues/119#issuecomment-1346407870. My guess is the player uses some value in the m3u8 file to track latency and when the swap happens that value is way different than in the original m3u8 so the latency value mess up

**Comment by stevenya97** [comment]
Yeah that was my guess as well, though it is strange that vaft is not affected. I understood it as the m3u8 swapping method is different between scripts but the m3u8 itself they fetch are the same? Must be different enough in some way to throw off whatever internal heuristic the player uses for it.

**Comment by pixeltris** [comment]
The major difference is video-swap-new reloads the player when it changes the active m3u8, so it could be related to that
