### ISSUE TITLE
[INVALID] [Feedback] TTV LOL PRO No Longer Works

### ISSUE THREAD

**Issue by JoLiKMC** [pixeltris/TwitchAdSolutions#288]
**09/30 Edit:**
Never mind.  I'm just "not using it right".  It'd be nice if the thing's instructions were a little more clear, on that front, but that's not any problem of this repository's.
—

~~Just tossing this out there: ''TTV LOL PRO'' doesn't seem to work anymore.  The extension, itself, warns that if the user is getting a lot of "commercial break in progress" videos that fiddling with the settings won't help, so that's pretty much admitting defeat right there.~~

However, the new ''uBlock Origin'' filter from this repository works. (The old one is dead and/or gone, it seems.)

Cheers and thank you!

**Comment by zGato** [comment]
The method the extension uses does work just fine. Now, if there are too many users in the public proxy pool, you may experience those. You can ask many users with their own proxies or the restricted ones that they've been totally fine for over a year, and continuing to do so.

Is VAFT/video-swap-new defeated because some very specific streams don't have the 360p embedded stream, thus the script is useless in those cases? No, clearly.

**Comment by JoLiKMC** [comment]
Well.  Alright, then.  It'd be nice if it worked out of the box with any consistency, but that's not really for discussion here.

Thank you for educating me.
