### ISSUE TITLE
Not Properly Working

### ISSUE THREAD

**Issue by Dustyragon** [pixeltris/TwitchAdSolutions#289]
It'll work for hours before suddenly a three minute long ad roll starts, and no amount of refreshing makes it bypass these ads. Even with the extra extensions and ublock origin it doesn't change anything. TTVLOLPRO doesn't work if the userscripts are active, it just says another adblock is in use. I have BOTH scripts active through Tampermonkey. Alongside having to refresh the player when it says there was an error, it tends to work then suddenly stop.

I'm using OperaGX.

EDIT since folks want to completely misunderstand things:
Combining things was a last ditch effort. TTVLOLPRO on it's own, ads got through. Ublock Origin alone, ads got through. The various extensions, ads got through. The userscripts, ads got through. Even with stuff combined, ads got through.

**Comment by zGato** [comment]
What isn't clear to you about this?
![image](https://github.com/user-attachments/assets/a528c653-525b-4c8f-8672-347f0a1b0f17)

**Comment by Dustyragon** [comment]
> What isn't clear to you about this? ![image](https://private-user-images.githubusercontent.com/88756568/373864082-a528c653-525b-4c8f-8672-347f0a1b0f17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjM3ODMsIm5iZiI6MTcyODEyMzQ4MywicGF0aCI6Ii84ODc1NjU2OC8zNzM4NjQwODItYTUyOGM2NTMtNTI1Yi00YzhmLTg2NzItMzQ3ZjBhMWIwZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDEwMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MGNjYmI0NDI0ODVmZTg2MzZlMGEzNzExZDk3OWNjYjk3MzlhNjE5Yjg4ZWNjZDAzNzJjNTA5MDY1M2FlMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7NWW1YPJigEZAWeyeCTIVZ-QI9p6S4WfMVD54iWxFF0)

What isn't clear about the fact I've tried basically everything and combining things was a last ditch effort? Can we drop the condescending attitude please? "What isn't clear" incites arguments.

**Comment by zGato** [comment]
You didn't clarify that at the start but whatever.
Drop me a DM on Discord, `zgato_`, and I'll take a look if I can help you with TTV LOL PRO, cause I highly doubt it's not working.

**Comment by pixeltris** [comment]
> TTVLOLPRO on it's own, ads got through.

The issues page for that project can be found here https://github.com/younesaassila/ttv-lol-pro/issues

> The various extensions, ads got through

Refer to the given extension's page for reporting issues

> Ublock Origin alone, ads got through

Twitch uses something called server side ad insertion (SSAI). These currently aren't handled by uBlock Origin. That being said, the solutions linked in this repo are specifically about SSAI. Twitch still runs client side ads which can look identical. So you will still need some type of adblocker (i.e. uBlock Origin) in combination with any solution linked in this repo.

> The userscripts, ads got through

The scripts are coded to disable themselves if they detect other Twitch specific ad blockers to prevent an infinite loading screen due to conflicts. This could be your problem. Closing this in favor of #294
