### ISSUE TITLE
No longer working on twitch 

### ISSUE THREAD

**Issue by TitanF1** [pixeltris/TwitchAdSolutions#294]
No longer functions

**Comment by pluscheck** [comment]
No longer working for me on twitch either.

**Comment by hubertskeltrix** [comment]
No longer working for me either

**Comment by Silliel** [comment]
No longer working for me either sadly

**Comment by Waldemard** [comment]
Same here, no longer works for at least a month...

**Comment by stevenya97** [comment]
Are you guys on Google Chrome? If you could comment what browser, platform, and script you are using that would be helpful to pixeltris.

If using uBlock Origin, could be linked to the extension being disabled/removed by Chrome for not supporting MV3. Could also be uBo not loading the script #200 , userscript is recommended. Try to migrate over to the userscript versions and see if that helps. If you want to try to diagnose, you can follow the steps [here](https://github.com/pixeltris/TwitchAdSolutions/issues/252#issuecomment-2145599172). You should see those messages in your browser console if the script has loaded properly regardless of how you install the scripts.

Am still seeing the userscript versions of vaft and video-swap-new working on my end on two different systems.

**Comment by pluscheck** [comment]
@stevenya97 yes. google chrome using userscript via tampermonkey. I am not using uBlock Origin

**Comment by stevenya97** [comment]
Gotcha, userscript has been smooth for me and I just loaded up a stream to test. Make sure to have video-swap-new OR vaft enabled, not both at the same time. Please try these [steps](https://github.com/pixeltris/TwitchAdSolutions/issues/252#issuecomment-2145599172) from another thread. You should see messages pertaining to ads being detected in the console. If not, the script did not load and a conflict with another script/solution exists on your end sadly(i.e. AdGuard Extra, TTV Pro, a VPN).

**Comment by drocologue** [comment]
@stevenya97 I use ublock in chrome and i try permanent link and update and i still get ads, what can i do

**Comment by JJDeakins1** [comment]
@drocologue not sure if this will help you but I am using TwitchAdSolutions (video-swap-new) in Google Chrome and noted in the developer console I was getting the following: 

`Multiple twitch adblockers installed. Skipping Worker hook (video-swap-new)'`

For what ever reason the script was detecting a conflict and not running. No other ad blockers or scripts were active so it should not have been occuring. I have since edited the userscript to `isTwitchWorker = false` to `isTwitchWorker = true`.

`// if (newWorker.toString() !== window.Worker.toString()) {
//     console.log('Multiple twitch adblockers installed. Skipping Worker hook (video-swap-new)');
//     isTwitchWorker = true;
// }`

**Comment by stevenya97** [comment]
@JJDeakins1 Do you perhaps use Adguard Extra or another adblocking script from the README? "Skipping worker hook" means it detects another script and lets that one take priority over video-swap-new. Both running same time could cause playback and buffering issues. If you have a clean install with no other extensions and userscripts that is indeed strange. Brave Browser also has their own internal scriptlet for Twitch ads that could interfere but you did mention being on Chrome

**Comment by pixeltris** [comment]
> No other ad blockers or scripts were active so it should not have been occuring

@JJDeakins1 could you log and compare `newWorker.toString()` / `window.Worker.toString()` to see why that code is skipping the hook?

**Comment by JJDeakins1** [comment]
@pixeltris I have uBlock Origin installed but disabled on Twitch and no other userscripts are active so not sure why a conflict is being produced.

FYI - image attached below of the two outputs in the console.

<img width="1902" alt="image" src="https://github.com/user-attachments/assets/ad5b87aa-e367-4675-90e5-afcda3427ecf">

**Comment by pixeltris** [comment]
Should be fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/722f5b96241ef1d92998b87f941690e47e475379. I changed it to check the hierarchy for twitch specific worker hooks.

@younesaassila you might want to do a similar hierarchy check in https://github.com/younesaassila/ttv-lol-pro/blob/aaf19619136ed778e558c2751e1c8b2a22b00560/src/page/page.ts#L54-L59, though if you copy the `isWorkerDoubleHooked` function without any changes to where you currently have your check ads would slip through in the following setup:
1. vaft injects / hooks the worker
2. 0 or more external scripts hook the worker
3. ttv-lol-pro hooks the worker
In this case `vaft` and `ttv-lol-pro` will check the hierarchy and no adblocking solution will be applied. This is because `ttv-lol-pro` always hooks the worker even if something already has hooked it. To mitigate that it'd probably make sense to check the hierarchy before hooking (but it'd still make sense to check inside the hook itself too). For example:
https://github.com/pixeltris/TwitchAdSolutions/blob/722f5b96241ef1d92998b87f941690e47e475379/video-swap-new/video-swap-new.user.js#L681-L686

**Comment by younesaassila** [comment]
> Should be fixed by https://github.com/pixeltris/TwitchAdSolutions/commit/722f5b96241ef1d92998b87f941690e47e475379. I changed it to check the hierarchy for twitch specific worker hooks.
> 
> 
> 
> @younesaassila you might want to do a similar hierarchy check in https://github.com/younesaassila/ttv-lol-pro/blob/aaf19619136ed778e558c2751e1c8b2a22b00560/src/page/page.ts#L54-L59, though if you copy the `isWorkerDoubleHooked` function without any changes to where you currently have your check ads would slip through in the following setup:
> 
> 1. vaft injects / hooks the worker
> 
> 2. 0 or more external scripts hook the worker
> 
> 3. ttv-lol-pro hooks the worker
> 
> In this case `vaft` and `ttv-lol-pro` will check the hierarchy and no adblocking solution will be applied. This is because `ttv-lol-pro` always hooks the worker even if something already has hooked it. To mitigate that it'd probably make sense to check the hierarchy before hooking (but it'd still make sense to check inside the hook itself too). For example:
> 
> https://github.com/pixeltris/TwitchAdSolutions/blob/722f5b96241ef1d92998b87f941690e47e475379/video-swap-new/video-swap-new.user.js#L681-L686

This bug only occurs if there is at least one external script hooking the worker in addition to Vaft and TTV LOL PRO, or have I misunderstood something?

**Comment by younesaassila** [comment]
But yeah it makes sense to check hierarchy in case of multiple scripts being used. Will definitely look into it. Thank you

**Comment by pixeltris** [comment]
> This bug only occurs if there is at least one external script hooking the worker in addition to Vaft and TTV LOL PRO, or have I misunderstood something?

That's correct, so in the case of this current issue (#294) your code isn't impacted as you check the worker for stuff like `'twitch'`:

1. ttv-lol-pro
2. external script

But you would get an infinite loading screen in this scenario:

1. ttv-lol-pro
2. some twitch solution / vaft fork which doesn't have any worker checks (i.e. Stream Cleaner)
3. external script

**Comment by prxshetty** [comment]
Try using Brave Browser with the chrome extension, it still should work !

**Comment by pixeltris** [comment]
@z28power check the console log for `hookWorkerFetch` which signifies that the script is being applied.

If it logs either of these then the script is disabling itself due to conflicting twitch solutions:

- `Twitch Worker is already hooked. Skipping (vaft)`
- `Multiple twitch adblockers installed. Skipping Worker hook (vaft)`

If that is the case add a `console.log` statement here:

https://github.com/pixeltris/TwitchAdSolutions/blob/aa5dff2cb54aa2a3e68304387050f01a1af08b32/vaft/vaft.user.js#L47-L49

Such that the code changes to this:

```js
if (workerString.includes(identifier) && workerString !== ourWorkerString) {
    console.log(workerString);
    return true;
}
```

Refresh the page to check the logged output. Validate that the logged output isn't some external twitch solution. If it is some external twitch solution then remove that external solution and try again. If the logged output is something unrelated to twitch then paste the logged output here and I can take a look at it.
