### ISSUE TITLE
video-swap-new stopped working

### ISSUE THREAD

**Issue by Tucsky** [pixeltris/TwitchAdSolutions#298]
the video-swap-new method stopped working since today.
I haven't changed anything to my ublock settings (`twitch.tv##+js(twitch-videoad)` in filters , `https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/video-swap-new/video-swap-new-ublock-origin.js` in userResourcesLocation) but yeah looks like they patched it :/

Using Chrome, no other extensions

**Comment by xxAlex7** [comment]
Stop using the uBlock Origin version, this version has known issues, use Tampermonkey + userscript instead. Don't forget to remove everything from uBlock Origin first.

**Comment by pixeltris** [comment]
Make sure you're on the latest version of the script, there was an update on the 3rd of November. I don't know in what situations uBlock Origin fetches the script but I assume it's only when the browser is opened. So try reopening your browser.

Also note this in the README of this project:

> *The scripts __may randomly stop being applied by uBlock Origin__ for unknown reasons ([#200](https://github.com/pixeltris/TwitchAdSolutions/issues/200)). It's recommended to use the userscript versions instead.*

If reopening the browser doesn't fix it then try the userscript version. If the userscript version doesn't work then refer to this:

---

Check the console log for `hookWorkerFetch` which signifies that the script is being applied.

If it logs either of the following then the script is disabling itself due to conflicting twitch solutions:

- `Twitch Worker is already hooked. Skipping (video-swap-new)`
- `Multiple twitch adblockers installed. Skipping Worker hook (video-swap-new)`

If that is the case add a `console.log` statement here:

https://github.com/pixeltris/TwitchAdSolutions/blob/aa5dff2cb54aa2a3e68304387050f01a1af08b32/vaft/vaft.user.js#L47-L49

Such that the code changes to this:

```js
if (workerString.includes(identifier) && workerString !== ourWorkerString) {
    console.log(workerString);
    return true;
}
```

Refresh the page to check the logged output. Validate that the logged output isn't some external twitch solution. If it is some external twitch solution then remove that external solution and try again. If the logged output is something unrelated to twitch then paste the logged output here and I can take a look at it.

**Comment by Moehrenquark** [comment]
> Stop using the uBlock Origin version, this version has known issues, use Tampermonkey + userscript instead. Don't forget to remove everything from uBlock Origin first.

im only using tampermonkey + script and have the same problem , getting ads on twitch since sunday

**Comment by Moehrenquark** [comment]
> Make sure you're on the latest version of the script, there was an update on the 3rd of November. I don't know in what situations uBlock Origin fetches the script but I assume it's only first load. So try reopening your browser or disable/enable the uBlock Origin extension.
> 
> Also note this in the README of this project:
> 
> > _The scripts **may randomly stop being applied by uBlock Origin** for unknown reasons ([#200](https://github.com/pixeltris/TwitchAdSolutions/issues/200)). It's recommended to use the userscript versions instead._
> 
> If reopening the browser doesn't fix it then try the userscript version. If the userscript version doesn't work then refer to this:
> 
> Check the console log for `hookWorkerFetch` which signifies that the script is being applied.
> 
> If it logs either of the following then the script is disabling itself due to conflicting twitch solutions:
> 
> * `Twitch Worker is already hooked. Skipping (video-swap-new)`
> * `Multiple twitch adblockers installed. Skipping Worker hook (video-swap-new)`
> 
> If that is the case add a `console.log` statement here:
> 
> https://github.com/pixeltris/TwitchAdSolutions/blob/aa5dff2cb54aa2a3e68304387050f01a1af08b32/video-swap-new/video-swap-new.user.js#L46-L48
> 
> Such that the code changes to this:
> 
> ```js
> if (workerString.includes(identifier) && workerString !== ourWorkerString) {
>     console.log(workerString);
>     return true;
> }
> ```
> 
> Refresh the page to check the logged output. Validate that the logged output isn't some external twitch solution. If it is some external twitch solution then remove that external solution and try again. If the logged output is something unrelated to twitch then paste the logged output here and I can take a look at it.

sadly its not working for me

**Comment by xxAlex7** [comment]
> im only using tampermonkey + script and have the same problem , getting ads on twitch since sunday

Works fine here

**Comment by pixeltris** [comment]
@Moehrenquark just above your comment I listed several steps. Please follow the steps and provide me information based on the output. I can't fix `"getting ads on twitch since sunday"` with no additional information. Thanks.

**Comment by Tucsky** [comment]
It's working again @pixeltris  @xxAlex7  (ublock origin way) 
sorry about that, not sure what happened... reopening the browser might have done it
