### ISSUE TITLE
Extensions for ad blocking by swapping to 480p.

### ISSUE THREAD

**Issue by saucettv** [pixeltris/TwitchAdSolutions#31]
I made an extension that adapts the pixeltris userscripts to make a kind of notify-replace. The extension will swap the video ads for a 480p version of the stream and switch back to original quality once the ad has finished. Firefox is version 2.1, Chrome is still waiting to be approved to 2.1. Only difference between 2.0 and 2.1, is I added ad tag urls to a block list in 2.1, to stop normal overlay ads that might slip through. Use UBlock Origin with it but don't use it with other Twitch specific userscripts or Twitch specific ad-block extensions, as it will cause conflicts. The link to the opensource code is below:

https://chrome.google.com/webstore/detail/video-ad-block-for-twitch/kgeglempfkhalebjlogemlmeakondflc

https://addons.mozilla.org/en-US/firefox/addon/video-ad-block-for-twitch

Opensource code:

https://gist.github.com/saucettv/0f85e9051c7d25aee67fdc033609fe1d

It all runs locally, no proxies or VPN's needed.

**Comment by pixeltris** [comment]
Cool, I like the idea of doing a pause/resume after ads have finished. It really simplifies the issues surrounding the transition and reduces code.

Have you tested this in midroll ads? One issue I see here is that the player wont like going from the regular stream to the lower resolution stream. This is because the sequencing will suddenly change. I think in this case you'll hit either error code 2000, or a loading wheel.

I didn't design the `div` on the top left properly. The code in this repo sort of gets away with it due to its short message `Waiting for ads to finish...`. But your longer message blocks the close button from being pressed when the stream is in mini-mode (i.e. whilst browsing streams). It might be worth looking at fixing the `div` or using a shorter message.

**Comment by saucettv** [comment]
Thanks, I tried testing mid-rolls by putting a timer in the code to fake a stitched ad at a certain point and it transitioned to the ad-free 480p and back ok, so hopefully it will be fine, but time will tell. The player itself doesn't seem to know that the quality has changed, at least from the controls. Yeah, I tried without the pause/resume but then I got a constant buffer, so the pause/resume is needed for sure. Thanks for the heads up on the div, will update that when I get around to it.

**Comment by pixeltris** [comment]
I hit a midroll and it seemed to do OK in terms of not getting stuck. The only issue is that it would keep doing a pause / play constantly for the duration of the ad. Not 100% sure why that would happen based on the logic of the code.

**Comment by saucettv** [comment]
Thanks for letting me know. I had a think about it today and I think the pause/play loop might be caused by Twitch doing the requests for the picture-by-picture feed in the background, as it would go through the code as an ad-free m3u8 and cause confusion. From their article it seems picture-by-picture is only run for mid-rolls, so it makes more sense. I'm thinking of maybe just blocking the picture-by-picture usher request when it comes through and hope it doesn't cause any other errors. For ref https://help.twitch.tv/s/article/picture-by-picture-ads?language=en_US

**Comment by saucettv** [comment]
https://gist.github.com/saucettv/0f85e9051c7d25aee67fdc033609fe1d I basically just made the gql request for the picture-by-picture feed have an empty body. Don't really like it, but it might work.

**Comment by saucettv** [comment]
I'm not really that clued up on how to Git, but I made a repository for the extension https://github.com/saucettv/VideoAdBlockForTwitch along with a userscript file for those that would prefer. Issues can then be added there if needed.

**Comment by pixeltris** [comment]
Closing this. This solution is in the README with all the relevant links.
