### ISSUE TITLE
(Notify Strip 1.5) Midrolls causes many pause-unpause spurts

### ISSUE THREAD

**Issue by TsukiZero** [pixeltris/TwitchAdSolutions#43]
It causes the so many of them I counted at lead 15 of those during a streamer-induced midroll and they happened every 1 to 3 seconds. I wonder: is there any way to mitigate it?

**Comment by pixeltris** [comment]
There are cases where the backup stream fails, so it refreshes the player (rather than serving you an ad). It might be the case that this is happening every time for some reason. When this happens you'll see in the console this message https://github.com/pixeltris/TwitchAdSolutions/blob/447776924fdb61c636320bf22ad3bf25adfb4fb1/base/base.user.js#L269

I have noticed that sometimes the Twitch player seems to request multiple streams at the same time (maybe different qualities, I never fully looked into this). I have observed that when this happens during midrolls the "blocking ads" message can alternate. It might be that what you're experiencing is related to this. Perhaps you have one with ads and one without ads which is why it's constantly pausing / playing. It could be the PYP player, but I'm not sure why it would invoke. `Video Ad-Block, for Twitch` has mitigation for this which I could add, but again it's weird why it would invoke in the first place (since the Twitch code never sees ads to invoke PYP).

So yea, I'll try and find the source of the multiple "streams" issue. It might be a bit hard as I haven't actually observed this behavior on my end (other than the alternating blocking message).

The latest version now uses the same algorithm as 1.5 btw, so you can use the latest.

**Comment by TsukiZero** [comment]
Sweet! Thanks for saving us from adpocalypse

**Comment by saucettv** [comment]
Yeah I'm also not really sure if putting in the mitigation for pbyp worked or not. I know they do the request when a user is in theater mode. At the time I also included:

        if (!textStr) {
            return textStr;
        }

        if (!textStr.includes(".ts")) {
            return textStr;
        }

Inside the processM3U8 function. I thought maybe there was an empty m3u8 request coming through somewhere causing it to not see an ad tag. I haven't had any complaints about the issue since though.

**Comment by pixeltris** [comment]
I had this happen the other day. There were multiple separate streams with no ads / ads which would result in pause/play being invoked on every other request. This happened to me when it bugged going into a midroll, causing a loading wheel (a separate issue which needs to be addressed). After pressing pause/play manually to fix the loading wheel, the described issue occurred.

https://github.com/pixeltris/TwitchAdSolutions/commit/e476b5d661277175033620bedebdc7708c9f12e6 now does this on a per-url basis which should hopefully stop this issue from happening.
