### ISSUE TITLE
Ads with notify-strip - 24/11/2021

### ISSUE THREAD

**Issue by mirko991** [pixeltris/TwitchAdSolutions#54]
Hi! Since today I am seeing ads that appear both at the beginning of the stream and during. Have you noticed it too?

**Comment by pixeltris** [comment]
Do you see preroll ads at a 100% rate? i.e. fully watch a preroll, then refresh, and repeat. Do you see an ad every time?

**Comment by mirko991** [comment]
> Do you see preroll ads at a 100% rate? i.e. fully watch a preroll, then refresh, and repeat. Do you see an ad every time?

No, it happens sometimes, not 100% rate. But ye, this never happened before (I never got a single ad with notify-strip enabled).

**Comment by pixeltris** [comment]
Interesting, well I'm not sure in this case then. It's still working correctly for me at the moment.

I mention 100% rate because if a variant of `bypass` is also being applied by you'll always see ads, even with `notify-strip` enabled. You can double check if this is happening by going to your network inspector and look for the gql request which includes `PlaybackAccessToken_Template`. If there is a header `Device-ID: twitch-web-wall-mason` then the `bypass` script is being applied.

This kind of thing happens if you're applying it as a userscript but have vanilla uBlock Origin or Brave (which apply a variant of `bypass`).

**Comment by mirko991** [comment]
> You can double check if this is happening by going to your network inspector and look for the gql request which includes `PlaybackAccessToken_Template`. If there is a header `Device-ID: twitch-web-wall-mason` then the `bypass` script is being applied.

Nothing, I just have a code in the Device-ID field.



> This kind of thing happens if you're applying it as a userscript but have vanilla uBlock Origin or Brave (which apply a variant of `bypass`).

I have uBO downloaded on the Chrome Web Store. But, as I said, I never had any problem with `notify-strip` enabled.

**Comment by pixeltris** [comment]
Yea that device id sounds fine. Not sure why it's failing, if you're actually seeing ads it's probably not being applied for some reason. There might be errors in the console.

You could also try `Video Ad-Block, for Twitch` which basically does the same thing.

**Comment by mirko991** [comment]
> There might be errors in the console.

Yeah, in the console there are a lot of errors like: `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`. IDK if that is normal.

**Comment by pixeltris** [comment]
Those don't sound related. The `Method called on deleted player instance` entry might be bad depending on the callstack. You can kinda confirm the script is being loaded properly by looking for this in the console (`getWasmWorkerUrl` on the callstack is the important signifier).

```
XHR finished loading: GET "blob:https://www.twitch.tv/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX".
getWasmWorkerUrl	@	VM6:122
Worker	@	VM6:45
...
```

And also make sure `fetch` is hooked by typing in the console `fetch.toString()` which should show code from this repo, as opposed to `ƒ fetch() { [native code] }`.

There might also be a small chance that the wrong worker is being hooked might silently fail.

I should probably add logging points in the script at some point so that it's clear if it loaded correctly or not, and make it spit out what it's seeing stream segment wise.

**Comment by mirko991** [comment]
> You can kinda confirm the script is being loaded properly by looking for this in the console (`getWasmWorkerUrl` on the callstack is the important signifier).

I can't find the call anywhere, unfortunately

> And also make sure `fetch` is hooked by typing in the console `fetch.toString()` which should show code from this repo, as opposed to `ƒ fetch() { [native code] }`

Confirm, it shows `ƒ fetch() { [native code] }`.

**Comment by pixeltris** [comment]
Hmm well that means the script isn't being injected at all. The first thing it does after being injected is [hook fetch](https://github.com/pixeltris/TwitchAdSolutions/blob/aad8946dab2bba951bb81c7730292fe595a7a6ae/notify-strip/notify-strip-ublock-origin.js#L600).

**Comment by mirko991** [comment]
It's this maybe? https://imgur.com/a/qfXcB4e

I tried to modify the value of `userResourcesLocation` to `unset` and then I changed it again with the right `notify-strip` link.

**Comment by pixeltris** [comment]
So it is loading? But not actually blocking anything? I'm not being too helpful here. I'll try making an edited script with log points when I get the chance.

That should just be a warning (I get it too). I don't think synchronous XHR has been removed from any chrome/firefox builds yet. But I should change that code at some point to be async somehow.

**Comment by mirko991** [comment]
Yes, it should work now (IDK why for some reason it wasn't able to load the script). 
Now I'm going out, when I have time I'll take a look on Twitch and I'll update you here.

**Comment by mirko991** [comment]
Aight, I can confirm it works again. IDK what happened yesterday...

**Comment by pixeltris** [comment]
Good to know. Maybe related to this https://github.com/pixeltris/TwitchAdSolutions/issues/29

At the time it would periodically stop working for me and simply re-enabling the script would fix the issue. I never got the chance to investigate as it hasn't happened to me since.

I'll keep an eye out.
