### ISSUE TITLE
Which script is the best?

### ISSUE THREAD

**Issue by ghost** [pixeltris/TwitchAdSolutions#67]
I have two questions about it. 1) Which script do you recommend to use between: "notify-strip", "notify-swap" and "low-res". 2) Once you have recommended me one of the 3 scripts which you suggest me to use between "uBlock" and "uBlock permalink"

**Comment by RedSnt** [comment]
I've been using the µBlock version of "notify-strip" + TTV LOL extension which seems to work seamlessly.

**Comment by TheEnhas** [comment]
`low-res` is the best if you have crappy internet or don't mind 480p, otherwise `notify-strip` if you're using a Chromium-based browser or `notify-swap` if Firefox. Also, use the permalink versions.

The proxy based (TTV.LOL and Purple AdBlock) extensions work well but can have serious buffering issues or downtime which is why I don't use them.
