### ISSUE TITLE
[Question] Is the code for the proxy server open source?

### ISSUE THREAD

**Issue by AugusDogus** [pixeltris/TwitchAdSolutions#8]
Basically title.

Do we currently have a way to host our own proxy server? 

Would be nice to have some fallback options incase the currently known hosted version fails.

**Comment by pixeltris** [comment]
There are a couple of people hosting a proxy for m3u8 files:

- https://got-greedy.corblimey.workers.dev/ (`Twitch Video Ad Blocker` by `TTV Ad Block`). This one takes the full url of the main m3u8.
- https://choosen.dev/stream/twitch/ (`Twitch AdBlock` by `ChoosenEye`). This one takes a channel name, and resolves the m3u8 url itself.

The implementation of both cases aren't publicly defined. All that's required to avoid ads proxy wise is hosting a server in a country that doesn't get ads. You can see which country the m3u8 files resolve from by looking at the m3u8 (the first link looks to be `GB`, and the second `DE`. `GB` should definitely get ads, so I'm not sure what they are doing.

The `proxy-m3u8` currently uses the second url, which just takes a channel name as the final arg to the url path. Creating your own proxy server involves doing the following:

- Host a web server in a country without ads
- Fetch the channel name from the last arg of the url e.g. `https://example.com/suburl/forsen` resolves to `forsen`
- Resolve the m3u8. There's a JavaScript example of doing that [here](https://github.com/pixeltris/TwitchAdSolutions/blob/0480745f7d4a18016b2c4428deb0d093507a95a7/base/base.user.js#L540) (this currently uses the old access token method), or C# [here](https://github.com/pixeltris/TwitchAdSolutions/blob/0480745f7d4a18016b2c4428deb0d093507a95a7/utils.cs#L241) using the new gql method.
- Once you have the m3u8 fetched from twitch, simply make that m3u8 text the response to the web request
- Add the url to https://github.com/pixeltris/TwitchAdSolutions/tree/master/proxy-m3u8 (or add it to just `.cfg` file, and re-run the `utils.exe build_scripts` thing.

There isn't an easy way to configure uBlock Origin scripts so that you can swap out the url. Not sure about userscript, but I think in both cases you need a single dedicated proxy url.

**Comment by trimbe** [comment]
I don't think it's that simple. I have a Google Cloud Function running in Germany (also tried Indonesia) proxying the access token -> m3u8 requests currently and I'm still getting the "commercial break" screen (not the anti-adblock screen) for prerolls and midrolls. Maybe these two other guys are proxying through their Turbo accounts?

**Comment by PureFallen** [comment]
DE (Germany) is getting ads normally as well. Both Proxies are interesting for sure. Probably opening the stream twice and switching the segments out whenever one serves ads? Would take a lot of power by that User Numbers, so i am not sure. I am surprised that even the bandwidth didn't collapse yet.
The Sourcecode would be interesting to locally host that proxy on like the same PC or a dedicated one in the network, but at the same time i can understand that they are not interested on the Twitch Ninjas to get that secret as well.

**Comment by Snake4life** [comment]
> DE (Germany) is getting ads normally as well. Both Proxies are interesting for sure. Probably opening the stream twice and switching the segments out whenever one serves ads? Would take a lot of power by that User Numbers, so i am not sure. I am surprised that even the bandwidth didn't collapse yet.
> The Sourcecode would be interesting to locally host that proxy on like the same PC or a dedicated one in the network, but at the same time i can understand that they are not interested on the Twitch Ninjas to get that secret as well.

tbh its pretty easy for an twitch dev to find out what the proxy is doing since they control their servers. There is 0 reason to keep the source closed.

**Comment by designgears** [comment]
I suspect this can be used to accomplish the same thing the proxies were doing. 

https://github.com/jasonbyrne/dynamic-hls-proxy

**Comment by douira** [comment]
Does this mean using a regular VPN targeting a country that doesn't get ads will have the same effect? Or does Twitch detect and block VPNs? Is there a list of no-ad countries to test this with? (or should I just randomly pick countries)

**Comment by PureFallen** [comment]
> 
> 
> > DE (Germany) is getting ads normally as well. Both Proxies are interesting for sure. Probably opening the stream twice and switching the segments out whenever one serves ads? Would take a lot of power by that User Numbers, so i am not sure. I am surprised that even the bandwidth didn't collapse yet.
> > The Sourcecode would be interesting to locally host that proxy on like the same PC or a dedicated one in the network, but at the same time i can understand that they are not interested on the Twitch Ninjas to get that secret as well.
> 
> tbh its pretty easy for an twitch dev to find out what the proxy is doing since they control their servers. There is 0 reason to keep the source closed other then trying to cashgrab via donations

Not saying it's impossible to find out, i guess it is mostly for slowing down the progress when you look at how quickly Twitch was with fixing stuff like that back when we worked with Playertypes..

**Comment by ceejayc7** [comment]
I tried implementing the server code on my own, but I'm getting the purple "Commerical break in progress" screen on the client. I'm using a Russian proxy on the server to retrieve the m3u8 and a modified version of the chrome extension to redirect to my server. Does Russia not work anymore? Or are there other countries that I can try? Maybe I messed up the implementation somewhere?

**Comment by pixeltris** [comment]
You'll have to try out a few different countries. I'd recommend getting a VPN/socks proxy which supports many locations and see which works the best. There have been conflicting reports of what works where so YMMV. See:

- https://old.reddit.com/r/Twitch/comments/kisdsy/i_did_a_little_test_regarding_ads_on_twitch_and/
- https://old.reddit.com/r/uBlockOrigin/comments/jjesgn/fix_for_ublock_origin_on_twitch_i_updated_the/gj9fumd/

**Comment by ceejayc7** [comment]
> You'll have to try out a few different countries. I'd recommend getting a VPN/socks proxy which supports many locations and see which works the best. There have been conflicting reports of what works where so YMMV. See:
> 
> * https://old.reddit.com/r/Twitch/comments/kisdsy/i_did_a_little_test_regarding_ads_on_twitch_and/
> * https://old.reddit.com/r/uBlockOrigin/comments/jjesgn/fix_for_ublock_origin_on_twitch_i_updated_the/gj9fumd/

Thanks for the info. On the Twitch extension itself, do you have any insight into [this code](https://robwu.nl/crxviewer/?crx=mipdalemhlhfenbikcloloheedmmecme&qf=js/background.js)? Specifically, there is a cookie being set and /auth is being called before the redirectUrl is returned. Since the original proxy is down, it's hard to figure out what it's actually doing. In my case, I removed all of the code and the function is simply returning the redirectUrl of the server.

**Comment by pixeltris** [comment]
The author of that extension didn't like people using their url. They took down the previous version of their extension due to that fact. I assume they added the auth thing as a crappy way of stopping people from probing the url directly (i.e. if the server doesn't see the cookie in the request, it will probably ignore it). The old version of that extension looked something like this (this might not be quite right, I never saved the old code):

```
function onBeforeRequest(details) {
    const match = /hls\/(\w+)\.m3u8/gim.exec(details.url);
    if (match !== null && match.length > 1) {
        return {
            redirectUrl: `https://choosen.dev/stream/${match[1]}`
        };
    } else {
        return {
            redirectUrl: details.url
        };
    }
}
chrome.webRequest.onBeforeRequest.addListener(
    onBeforeRequest, {
        urls: ["https://usher.ttvnw.net/api/channel/hls/*"]
    },
    ["blocking", "extraHeaders"]
);
```

**Comment by ceejayc7** [comment]
I got it working. FWIW, I was missing the "Device-ID" header in the gql POST for the PlaybackAccessToken_Template query.

**Comment by jamesdrudolph** [comment]
> 
> 
> I got it working. FWIW, I was missing the "Device-ID" header in the gql POST for the PlaybackAccessToken_Template query.

Is your Russian proxy still working? I've created a proxy in Bahrain and São Paulo and neither are working. Not sure if it is my implementation or the country.

**Comment by ceejayc7** [comment]
> > I got it working. FWIW, I was missing the "Device-ID" header in the gql POST for the PlaybackAccessToken_Template query.
> 
> Is your Russian proxy still working? I've created a proxy in Bahrain and São Paulo and neither are working. Not sure if it is my implementation or the country.

Yes, it's still working for me.

**Comment by KillaBoi** [comment]
I'm contemplating setting up a private server (for me and my friends) which uses a turbo enabled account to essentially do what the above would do, is there anything special I have to do besides authentication with that specific account by any chance? I saw in another issue that you were going to make some example code about proxying m3u8's, is that still in progress?

Thanks for the useful repo and the tips/advice/info in these issues, they're very useful!

**Comment by arthurbolsoni** [comment]
> Not sure if it is my implementation or the country.

in brasil have ads. a lot.

**Comment by Zibbp** [comment]
I've set up a simple server to successfully return the m3u8 and modified the extension to use my backend. The issue I'm facing is whenever I open a new stream I receive a "commercial break in progress" screen. Once that is over I never see an ad throughout a stream. Does anyone know how to get rid of this initial 15 second "ad" on each stream load?

![commercial break](https://i.imgur.com/XLCwjcf.png)

**Comment by pixeltris** [comment]
Make sure you have the `Device-ID` header in the gql request as mentioned above, and try a few different countries. Also make sure your `playerType` is `site`.

**Comment by arthurbolsoni** [comment]
> I've set up a simple server to successfully return the m3u8 and modified the extension to use my backend. The issue I'm facing is whenever I open a new stream I receive a "commercial break in progress" screen. Once that is over I never see an ad throughout a stream. Does anyone know how to get rid of this initial 15 second "ad" on each stream load?

i do the same, the first 15sec is the problem, i think that buy twitch turbo for the server should resolve that. i think

**Comment by arthurbolsoni** [comment]
i gonna try in Ukraine later time

**Comment by jamesdrudolph** [comment]
> 
> 
> Make sure you have the `Device-ID` header in the gql request as mentioned above, and try a few different countries. Also make sure your `playerType` is `site`.

FYI, to anyone using [this](https://github.com/pixeltris/TwitchAdSolutions/blob/master/utils.cs) code for retrieving the M3U8, the Device-ID header _is_ sent, its just blank. You'll need to fix the `ProcessCoookies()` function.

**Comment by arthurbolsoni** [comment]
i put a random 32 caracteres devide-id header and work

**Comment by pixeltris** [comment]
I've added some example server code + a browser extension compatible with Chrome / Firefox. It might be a useful starting point for some, but due to the limitations of the web server in the code I wouldn't recommend it (tricky to configure https support).

https://github.com/pixeltris/TwitchAdSolutions/tree/master/proxy

**Comment by dozzzz02** [comment]
@pixeltris Don't know if I'm doing it correctly but using the proxy method and I just get

_There was a network error. Pleasy try again. (Error #2000)_

I've used a Russian proxy. Does the problem lie with it being Russian or does Twitch not like this?

**Comment by pixeltris** [comment]
You're probably running into CORS errors. The mixed content (http on https) is an issue. Check your browser console or network inspector to see what's happening to your requests.

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/

i do that extension and i am doing for keep online. i gonna publish the code too. it is in firefox and google store.

**Comment by pixeltris** [comment]
Closing this as there's now code available to host your own proxy server as provided by https://github.com/arthurbolsoni/Purple-adblock/ which has a JavaScript and a python implementation, along with browser code.

Additionally it's stated server code will be put in the TTV-LOL repo at some point https://github.com/TTV-LOL/extensions (as mentioned in https://github.com/TTV-LOL/extensions/issues/1).

There's also this, but I wouldn't recommend using it https://github.com/pixeltris/TwitchAdSolutions/tree/master/proxy
