### ISSUE TITLE
Notify scripts no longer working (US)

### ISSUE THREAD

**Issue by umbralOptimatum** [pixeltris/TwitchAdSolutions#83]
As of today, notify-strip and notify-swap are no longer working for me. Both just show a black player; strip constantly pauses and unpauses while swap shows the spinning loading circle. Vaft is working fine. I'm using uBlock 1.44.0 on Firefox 103.0.2 with the most recent script permalinks.

**Comment by pixeltris** [comment]
Thanks for the report. This has happened due to an unfortunate side effect of the device id swapping that was implemented. Twitch is doing A/B testing of this new commercial screen and some device ids get it, some don't. The switched device id over the weekend got it. I've now changed it to a fixed device id of '1'.

**Comment by sk8rslim** [comment]
Yep neither is working for me on Chorme or Firefox.

**Comment by stevenya97** [comment]
Please reference #84 and the updated readme for updated recommended ad blocking methods. Notify-strip is now legacy as Twitch themselves have broken this functionality. Current methods commonly involve the use of proxies for now
