### ISSUE TITLE
vaft ublock script causing paused video to start playing after switching tab

### ISSUE THREAD

**Issue by Californ1a** [pixeltris/TwitchAdSolutions#91]
If you go to an offline channel, Twitch automatically plays that channel's most recent past broadcast at the top of the page. If you pause it, go to their highlights/uploads (or any other video list), and middle click on a video to open it in a new tab, then when you swap to that tab, vaft starts playing the most recent past broadcast at the top of the video list page in the inactive tab.

This wasn't an issue with notify-strip or notify-swap, but since those are broken I'm having to use vaft now which has this issue that forces me to close the video list page since it keeps hitting play on that video at the top every time I switch tabs.

**Comment by pixeltris** [comment]
https://github.com/pixeltris/TwitchAdSolutions/blob/05c13983eb15c966810d93473a96c28aefc7aea0/vaft/vaft.user.js#L40

This should probably be changed to `block` rather than `process`. What it does is described here:

https://github.com/pixeltris/TwitchAdSolutions/blob/05c13983eb15c966810d93473a96c28aefc7aea0/vaft/vaft.user.js#L37-L38

https://github.com/pixeltris/TwitchAdSolutions/blob/05c13983eb15c966810d93473a96c28aefc7aea0/vaft/vaft.user.js#L750

It causes some weird side effects as you have noticed as well as when you return to a tab after a while it briefly pauses/plays the stream which looks weird.

This is more of an issue for the repo where the code is maintained at https://github.com/cleanlock/VideoAdBlockForTwitch (vaft is just that repo as a script) so I'm going to close this but feel free to open an issue there (or a PR with the change described above) and you could link back to this issue for some context.

**Comment by pixeltris** [comment]
Actually there's already an open issue for this https://github.com/cleanlock/VideoAdBlockForTwitch/issues/47
