### ISSUE TITLE
vaft Userscript Unpauses Streams within Embedded iframes

### ISSUE THREAD

**Issue by knakamura8** [pixeltris/TwitchAdSolutions#94]
Some sites have Twitch streams embedded in iframes within them.  Even if the user manually pauses the stream, vaft will unpause the stream after a several second timeout.  Perhaps some way of detecting user-intention pause, or a flag at the top of the script wherein a user can disable embed behavior, or even a flag to merely disable when within an iframe.

Clarification: I do realize that one can set an option in their script manager to only allow the script to run in the top frame, but perhaps this is something to look into, regardless.  Maybe it should just be a wontfix, however... or maybe @noframes flag at the top?

**Comment by pixeltris** [comment]
It doesn't seem to be doing that for me on https://twitchls.com

But the issue is probably the same as this:
- https://github.com/pixeltris/TwitchAdSolutions/issues/91
- https://github.com/cleanlock/VideoAdBlockForTwitch/issues/47

I might make that change I mentioned in the first issue as I don't think the functionality brings any real benefit.

**Comment by pixeltris** [comment]
I've pushed an update to it. Hopefully that fixes it.

**Comment by knakamura8** [comment]
OK, awesome!  Ah, that is interesting, thank you for the quick push.  I will run some tests later and let you know!

**Comment by knakamura8** [comment]
This fix seems to be working, thanks @pixeltris !
